version: '3.3'
services:
  db:
    image: postgres
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    image: localhost:5000/sample-rails-app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
